// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;

namespace RocketExplorer.Ethereum.RocketMegapoolDelegate.ContractDefinition
{
    public partial class Withdrawal : WithdrawalBase { }

    public class WithdrawalBase 
    {
        [Parameter("uint64", "index", 1)]
        public virtual ulong Index { get; set; }
        [Parameter("uint64", "validatorIndex", 2)]
        public virtual ulong ValidatorIndex { get; set; }
        [Parameter("bytes20", "withdrawalCredentials", 3)]
        public virtual byte[] WithdrawalCredentials { get; set; }
        [Parameter("uint64", "amountInGwei", 4)]
        public virtual ulong AmountInGwei { get; set; }
    }
}
