// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Contracts.CQS;
using Nethereum.Contracts;
using System.Threading;

namespace RocketExplorer.Ethereum.RocketMinipoolDelegate.ContractDefinition
{


    public partial class RocketMinipoolDelegateDeployment : RocketMinipoolDelegateDeploymentBase
    {
        public RocketMinipoolDelegateDeployment() : base(BYTECODE) { }
        public RocketMinipoolDelegateDeployment(string byteCode) : base(byteCode) { }
    }

    public class RocketMinipoolDelegateDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = """
[
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "previousBondAmount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "newBondAmount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "BondReduced",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "from",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "EtherDeposited",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "executed",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "nodeAmount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "userAmount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "totalBalance",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "EtherWithdrawalProcessed",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "to",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "EtherWithdrawn",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "bytes",
				"name": "validatorPubkey",
				"type": "bytes"
			},
			{
				"indexed": false,
				"internalType": "bytes",
				"name": "validatorSignature",
				"type": "bytes"
			},
			{
				"indexed": false,
				"internalType": "bytes32",
				"name": "depositDataRoot",
				"type": "bytes32"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "bytes",
				"name": "withdrawalCredentials",
				"type": "bytes"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "MinipoolPrestaked",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "MinipoolPromoted",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "MinipoolScrubbed",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "bondAmount",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "currentBalance",
				"type": "uint256"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "MinipoolVacancyPrepared",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "member",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "ScrubVoted",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "uint8",
				"name": "status",
				"type": "uint8"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "StatusUpdated",
		"type": "event"
	},
	{
		"inputs": [],
		"name": "beginUserDistribute",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_balance",
				"type": "uint256"
			}
		],
		"name": "calculateNodeShare",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_balance",
				"type": "uint256"
			}
		],
		"name": "calculateUserShare",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "canPromote",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "canStake",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "close",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "deposit",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "dissolve",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bool",
				"name": "_rewardsOnly",
				"type": "bool"
			}
		],
		"name": "distributeBalance",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "finalise",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getDepositType",
		"outputs": [
			{
				"internalType": "enum MinipoolDeposit",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getFinalised",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getNodeAddress",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getNodeDepositAssigned",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getNodeDepositBalance",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getNodeFee",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getNodeRefundBalance",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getNodeTopUpValue",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getPreLaunchValue",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getPreMigrationBalance",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_member",
				"type": "address"
			}
		],
		"name": "getScrubVoted",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getStatus",
		"outputs": [
			{
				"internalType": "enum MinipoolStatus",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getStatusBlock",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getStatusTime",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getTotalScrubVotes",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getUserDepositAssigned",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getUserDepositAssignedTime",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getUserDepositBalance",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getUserDistributed",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getVacant",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_nodeAddress",
				"type": "address"
			}
		],
		"name": "initialise",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_bondValue",
				"type": "uint256"
			},
			{
				"internalType": "bytes",
				"name": "_validatorPubkey",
				"type": "bytes"
			},
			{
				"internalType": "bytes",
				"name": "_validatorSignature",
				"type": "bytes"
			},
			{
				"internalType": "bytes32",
				"name": "_depositDataRoot",
				"type": "bytes32"
			}
		],
		"name": "preDeposit",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_bondAmount",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "_currentBalance",
				"type": "uint256"
			}
		],
		"name": "prepareVacancy",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "promote",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "reduceBondAmount",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "refund",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "slash",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes",
				"name": "_validatorSignature",
				"type": "bytes"
			},
			{
				"internalType": "bytes32",
				"name": "_depositDataRoot",
				"type": "bytes32"
			}
		],
		"name": "stake",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "userDeposit",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "userDistributeAllowed",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "version",
		"outputs": [
			{
				"internalType": "uint8",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "voteScrub",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	}
]
""";
        public RocketMinipoolDelegateDeploymentBase() : base(BYTECODE) { }
        public RocketMinipoolDelegateDeploymentBase(string byteCode) : base(byteCode) { }

    }

    public partial class BeginUserDistributeFunction : BeginUserDistributeFunctionBase { }

    [Function("beginUserDistribute")]
    public class BeginUserDistributeFunctionBase : FunctionMessage
    {

    }

    public partial class CalculateNodeShareFunction : CalculateNodeShareFunctionBase { }

    [Function("calculateNodeShare", "uint256")]
    public class CalculateNodeShareFunctionBase : FunctionMessage
    {
        [Parameter("uint256", "_balance", 1)]
        public virtual BigInteger Balance { get; set; }
    }

    public partial class CalculateUserShareFunction : CalculateUserShareFunctionBase { }

    [Function("calculateUserShare", "uint256")]
    public class CalculateUserShareFunctionBase : FunctionMessage
    {
        [Parameter("uint256", "_balance", 1)]
        public virtual BigInteger Balance { get; set; }
    }

    public partial class CanPromoteFunction : CanPromoteFunctionBase { }

    [Function("canPromote", "bool")]
    public class CanPromoteFunctionBase : FunctionMessage
    {

    }

    public partial class CanStakeFunction : CanStakeFunctionBase { }

    [Function("canStake", "bool")]
    public class CanStakeFunctionBase : FunctionMessage
    {

    }

    public partial class CloseFunction : CloseFunctionBase { }

    [Function("close")]
    public class CloseFunctionBase : FunctionMessage
    {

    }

    public partial class DepositFunction : DepositFunctionBase { }

    [Function("deposit")]
    public class DepositFunctionBase : FunctionMessage
    {

    }

    public partial class DissolveFunction : DissolveFunctionBase { }

    [Function("dissolve")]
    public class DissolveFunctionBase : FunctionMessage
    {

    }

    public partial class DistributeBalanceFunction : DistributeBalanceFunctionBase { }

    [Function("distributeBalance")]
    public class DistributeBalanceFunctionBase : FunctionMessage
    {
        [Parameter("bool", "_rewardsOnly", 1)]
        public virtual bool RewardsOnly { get; set; }
    }

    public partial class FinaliseFunction : FinaliseFunctionBase { }

    [Function("finalise")]
    public class FinaliseFunctionBase : FunctionMessage
    {

    }

    public partial class GetDepositTypeFunction : GetDepositTypeFunctionBase { }

    [Function("getDepositType", "uint8")]
    public class GetDepositTypeFunctionBase : FunctionMessage
    {

    }

    public partial class GetFinalisedFunction : GetFinalisedFunctionBase { }

    [Function("getFinalised", "bool")]
    public class GetFinalisedFunctionBase : FunctionMessage
    {

    }

    public partial class GetNodeAddressFunction : GetNodeAddressFunctionBase { }

    [Function("getNodeAddress", "address")]
    public class GetNodeAddressFunctionBase : FunctionMessage
    {

    }

    public partial class GetNodeDepositAssignedFunction : GetNodeDepositAssignedFunctionBase { }

    [Function("getNodeDepositAssigned", "bool")]
    public class GetNodeDepositAssignedFunctionBase : FunctionMessage
    {

    }

    public partial class GetNodeDepositBalanceFunction : GetNodeDepositBalanceFunctionBase { }

    [Function("getNodeDepositBalance", "uint256")]
    public class GetNodeDepositBalanceFunctionBase : FunctionMessage
    {

    }

    public partial class GetNodeFeeFunction : GetNodeFeeFunctionBase { }

    [Function("getNodeFee", "uint256")]
    public class GetNodeFeeFunctionBase : FunctionMessage
    {

    }

    public partial class GetNodeRefundBalanceFunction : GetNodeRefundBalanceFunctionBase { }

    [Function("getNodeRefundBalance", "uint256")]
    public class GetNodeRefundBalanceFunctionBase : FunctionMessage
    {

    }

    public partial class GetNodeTopUpValueFunction : GetNodeTopUpValueFunctionBase { }

    [Function("getNodeTopUpValue", "uint256")]
    public class GetNodeTopUpValueFunctionBase : FunctionMessage
    {

    }

    public partial class GetPreLaunchValueFunction : GetPreLaunchValueFunctionBase { }

    [Function("getPreLaunchValue", "uint256")]
    public class GetPreLaunchValueFunctionBase : FunctionMessage
    {

    }

    public partial class GetPreMigrationBalanceFunction : GetPreMigrationBalanceFunctionBase { }

    [Function("getPreMigrationBalance", "uint256")]
    public class GetPreMigrationBalanceFunctionBase : FunctionMessage
    {

    }

    public partial class GetScrubVotedFunction : GetScrubVotedFunctionBase { }

    [Function("getScrubVoted", "bool")]
    public class GetScrubVotedFunctionBase : FunctionMessage
    {
        [Parameter("address", "_member", 1)]
        public virtual string Member { get; set; }
    }

    public partial class GetStatusFunction : GetStatusFunctionBase { }

    [Function("getStatus", "uint8")]
    public class GetStatusFunctionBase : FunctionMessage
    {

    }

    public partial class GetStatusBlockFunction : GetStatusBlockFunctionBase { }

    [Function("getStatusBlock", "uint256")]
    public class GetStatusBlockFunctionBase : FunctionMessage
    {

    }

    public partial class GetStatusTimeFunction : GetStatusTimeFunctionBase { }

    [Function("getStatusTime", "uint256")]
    public class GetStatusTimeFunctionBase : FunctionMessage
    {

    }

    public partial class GetTotalScrubVotesFunction : GetTotalScrubVotesFunctionBase { }

    [Function("getTotalScrubVotes", "uint256")]
    public class GetTotalScrubVotesFunctionBase : FunctionMessage
    {

    }

    public partial class GetUserDepositAssignedFunction : GetUserDepositAssignedFunctionBase { }

    [Function("getUserDepositAssigned", "bool")]
    public class GetUserDepositAssignedFunctionBase : FunctionMessage
    {

    }

    public partial class GetUserDepositAssignedTimeFunction : GetUserDepositAssignedTimeFunctionBase { }

    [Function("getUserDepositAssignedTime", "uint256")]
    public class GetUserDepositAssignedTimeFunctionBase : FunctionMessage
    {

    }

    public partial class GetUserDepositBalanceFunction : GetUserDepositBalanceFunctionBase { }

    [Function("getUserDepositBalance", "uint256")]
    public class GetUserDepositBalanceFunctionBase : FunctionMessage
    {

    }

    public partial class GetUserDistributedFunction : GetUserDistributedFunctionBase { }

    [Function("getUserDistributed", "bool")]
    public class GetUserDistributedFunctionBase : FunctionMessage
    {

    }

    public partial class GetVacantFunction : GetVacantFunctionBase { }

    [Function("getVacant", "bool")]
    public class GetVacantFunctionBase : FunctionMessage
    {

    }

    public partial class InitialiseFunction : InitialiseFunctionBase { }

    [Function("initialise")]
    public class InitialiseFunctionBase : FunctionMessage
    {
        [Parameter("address", "_nodeAddress", 1)]
        public virtual string NodeAddress { get; set; }
    }

    public partial class PreDepositFunction : PreDepositFunctionBase { }

    [Function("preDeposit")]
    public class PreDepositFunctionBase : FunctionMessage
    {
        [Parameter("uint256", "_bondValue", 1)]
        public virtual BigInteger BondValue { get; set; }
        [Parameter("bytes", "_validatorPubkey", 2)]
        public virtual byte[] ValidatorPubkey { get; set; }
        [Parameter("bytes", "_validatorSignature", 3)]
        public virtual byte[] ValidatorSignature { get; set; }
        [Parameter("bytes32", "_depositDataRoot", 4)]
        public virtual byte[] DepositDataRoot { get; set; }
    }

    public partial class PrepareVacancyFunction : PrepareVacancyFunctionBase { }

    [Function("prepareVacancy")]
    public class PrepareVacancyFunctionBase : FunctionMessage
    {
        [Parameter("uint256", "_bondAmount", 1)]
        public virtual BigInteger BondAmount { get; set; }
        [Parameter("uint256", "_currentBalance", 2)]
        public virtual BigInteger CurrentBalance { get; set; }
    }

    public partial class PromoteFunction : PromoteFunctionBase { }

    [Function("promote")]
    public class PromoteFunctionBase : FunctionMessage
    {

    }

    public partial class ReduceBondAmountFunction : ReduceBondAmountFunctionBase { }

    [Function("reduceBondAmount")]
    public class ReduceBondAmountFunctionBase : FunctionMessage
    {

    }

    public partial class RefundFunction : RefundFunctionBase { }

    [Function("refund")]
    public class RefundFunctionBase : FunctionMessage
    {

    }

    public partial class SlashFunction : SlashFunctionBase { }

    [Function("slash")]
    public class SlashFunctionBase : FunctionMessage
    {

    }

    public partial class StakeFunction : StakeFunctionBase { }

    [Function("stake")]
    public class StakeFunctionBase : FunctionMessage
    {
        [Parameter("bytes", "_validatorSignature", 1)]
        public virtual byte[] ValidatorSignature { get; set; }
        [Parameter("bytes32", "_depositDataRoot", 2)]
        public virtual byte[] DepositDataRoot { get; set; }
    }

    public partial class UserDepositFunction : UserDepositFunctionBase { }

    [Function("userDeposit")]
    public class UserDepositFunctionBase : FunctionMessage
    {

    }

    public partial class UserDistributeAllowedFunction : UserDistributeAllowedFunctionBase { }

    [Function("userDistributeAllowed", "bool")]
    public class UserDistributeAllowedFunctionBase : FunctionMessage
    {

    }

    public partial class VersionFunction : VersionFunctionBase { }

    [Function("version", "uint8")]
    public class VersionFunctionBase : FunctionMessage
    {

    }

    public partial class VoteScrubFunction : VoteScrubFunctionBase { }

    [Function("voteScrub")]
    public class VoteScrubFunctionBase : FunctionMessage
    {

    }

    public partial class BondReducedEventDTO : BondReducedEventDTOBase { }

    [Event("BondReduced")]
    public class BondReducedEventDTOBase : IEventDTO
    {
        [Parameter("uint256", "previousBondAmount", 1, false )]
        public virtual BigInteger PreviousBondAmount { get; set; }
        [Parameter("uint256", "newBondAmount", 2, false )]
        public virtual BigInteger NewBondAmount { get; set; }
        [Parameter("uint256", "time", 3, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class EtherDepositedEventDTO : EtherDepositedEventDTOBase { }

    [Event("EtherDeposited")]
    public class EtherDepositedEventDTOBase : IEventDTO
    {
        [Parameter("address", "from", 1, true )]
        public virtual string From { get; set; }
        [Parameter("uint256", "amount", 2, false )]
        public virtual BigInteger Amount { get; set; }
        [Parameter("uint256", "time", 3, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class EtherWithdrawalProcessedEventDTO : EtherWithdrawalProcessedEventDTOBase { }

    [Event("EtherWithdrawalProcessed")]
    public class EtherWithdrawalProcessedEventDTOBase : IEventDTO
    {
        [Parameter("address", "executed", 1, true )]
        public virtual string Executed { get; set; }
        [Parameter("uint256", "nodeAmount", 2, false )]
        public virtual BigInteger NodeAmount { get; set; }
        [Parameter("uint256", "userAmount", 3, false )]
        public virtual BigInteger UserAmount { get; set; }
        [Parameter("uint256", "totalBalance", 4, false )]
        public virtual BigInteger TotalBalance { get; set; }
        [Parameter("uint256", "time", 5, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class EtherWithdrawnEventDTO : EtherWithdrawnEventDTOBase { }

    [Event("EtherWithdrawn")]
    public class EtherWithdrawnEventDTOBase : IEventDTO
    {
        [Parameter("address", "to", 1, true )]
        public virtual string To { get; set; }
        [Parameter("uint256", "amount", 2, false )]
        public virtual BigInteger Amount { get; set; }
        [Parameter("uint256", "time", 3, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class MinipoolPrestakedEventDTO : MinipoolPrestakedEventDTOBase { }

    [Event("MinipoolPrestaked")]
    public class MinipoolPrestakedEventDTOBase : IEventDTO
    {
        [Parameter("bytes", "validatorPubkey", 1, false )]
        public virtual byte[] ValidatorPubkey { get; set; }
        [Parameter("bytes", "validatorSignature", 2, false )]
        public virtual byte[] ValidatorSignature { get; set; }
        [Parameter("bytes32", "depositDataRoot", 3, false )]
        public virtual byte[] DepositDataRoot { get; set; }
        [Parameter("uint256", "amount", 4, false )]
        public virtual BigInteger Amount { get; set; }
        [Parameter("bytes", "withdrawalCredentials", 5, false )]
        public virtual byte[] WithdrawalCredentials { get; set; }
        [Parameter("uint256", "time", 6, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class MinipoolPromotedEventDTO : MinipoolPromotedEventDTOBase { }

    [Event("MinipoolPromoted")]
    public class MinipoolPromotedEventDTOBase : IEventDTO
    {
        [Parameter("uint256", "time", 1, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class MinipoolScrubbedEventDTO : MinipoolScrubbedEventDTOBase { }

    [Event("MinipoolScrubbed")]
    public class MinipoolScrubbedEventDTOBase : IEventDTO
    {
        [Parameter("uint256", "time", 1, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class MinipoolVacancyPreparedEventDTO : MinipoolVacancyPreparedEventDTOBase { }

    [Event("MinipoolVacancyPrepared")]
    public class MinipoolVacancyPreparedEventDTOBase : IEventDTO
    {
        [Parameter("uint256", "bondAmount", 1, false )]
        public virtual BigInteger BondAmount { get; set; }
        [Parameter("uint256", "currentBalance", 2, false )]
        public virtual BigInteger CurrentBalance { get; set; }
        [Parameter("uint256", "time", 3, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class ScrubVotedEventDTO : ScrubVotedEventDTOBase { }

    [Event("ScrubVoted")]
    public class ScrubVotedEventDTOBase : IEventDTO
    {
        [Parameter("address", "member", 1, true )]
        public virtual string Member { get; set; }
        [Parameter("uint256", "time", 2, false )]
        public virtual BigInteger Time { get; set; }
    }

    public partial class StatusUpdatedEventDTO : StatusUpdatedEventDTOBase { }

    [Event("StatusUpdated")]
    public class StatusUpdatedEventDTOBase : IEventDTO
    {
        [Parameter("uint8", "status", 1, true )]
        public virtual byte Status { get; set; }
        [Parameter("uint256", "time", 2, false )]
        public virtual BigInteger Time { get; set; }
    }



    public partial class CalculateNodeShareOutputDTO : CalculateNodeShareOutputDTOBase { }

    [FunctionOutput]
    public class CalculateNodeShareOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class CalculateUserShareOutputDTO : CalculateUserShareOutputDTOBase { }

    [FunctionOutput]
    public class CalculateUserShareOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class CanPromoteOutputDTO : CanPromoteOutputDTOBase { }

    [FunctionOutput]
    public class CanPromoteOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class CanStakeOutputDTO : CanStakeOutputDTOBase { }

    [FunctionOutput]
    public class CanStakeOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }











    public partial class GetDepositTypeOutputDTO : GetDepositTypeOutputDTOBase { }

    [FunctionOutput]
    public class GetDepositTypeOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint8", "", 1)]
        public virtual byte ReturnValue1 { get; set; }
    }

    public partial class GetFinalisedOutputDTO : GetFinalisedOutputDTOBase { }

    [FunctionOutput]
    public class GetFinalisedOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class GetNodeAddressOutputDTO : GetNodeAddressOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeAddressOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("address", "", 1)]
        public virtual string ReturnValue1 { get; set; }
    }

    public partial class GetNodeDepositAssignedOutputDTO : GetNodeDepositAssignedOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeDepositAssignedOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class GetNodeDepositBalanceOutputDTO : GetNodeDepositBalanceOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeDepositBalanceOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetNodeFeeOutputDTO : GetNodeFeeOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeFeeOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetNodeRefundBalanceOutputDTO : GetNodeRefundBalanceOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeRefundBalanceOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetNodeTopUpValueOutputDTO : GetNodeTopUpValueOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeTopUpValueOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetPreLaunchValueOutputDTO : GetPreLaunchValueOutputDTOBase { }

    [FunctionOutput]
    public class GetPreLaunchValueOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetPreMigrationBalanceOutputDTO : GetPreMigrationBalanceOutputDTOBase { }

    [FunctionOutput]
    public class GetPreMigrationBalanceOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetScrubVotedOutputDTO : GetScrubVotedOutputDTOBase { }

    [FunctionOutput]
    public class GetScrubVotedOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class GetStatusOutputDTO : GetStatusOutputDTOBase { }

    [FunctionOutput]
    public class GetStatusOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint8", "", 1)]
        public virtual byte ReturnValue1 { get; set; }
    }

    public partial class GetStatusBlockOutputDTO : GetStatusBlockOutputDTOBase { }

    [FunctionOutput]
    public class GetStatusBlockOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetStatusTimeOutputDTO : GetStatusTimeOutputDTOBase { }

    [FunctionOutput]
    public class GetStatusTimeOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetTotalScrubVotesOutputDTO : GetTotalScrubVotesOutputDTOBase { }

    [FunctionOutput]
    public class GetTotalScrubVotesOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetUserDepositAssignedOutputDTO : GetUserDepositAssignedOutputDTOBase { }

    [FunctionOutput]
    public class GetUserDepositAssignedOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class GetUserDepositAssignedTimeOutputDTO : GetUserDepositAssignedTimeOutputDTOBase { }

    [FunctionOutput]
    public class GetUserDepositAssignedTimeOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetUserDepositBalanceOutputDTO : GetUserDepositBalanceOutputDTOBase { }

    [FunctionOutput]
    public class GetUserDepositBalanceOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetUserDistributedOutputDTO : GetUserDistributedOutputDTOBase { }

    [FunctionOutput]
    public class GetUserDistributedOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class GetVacantOutputDTO : GetVacantOutputDTOBase { }

    [FunctionOutput]
    public class GetVacantOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }



















    public partial class UserDistributeAllowedOutputDTO : UserDistributeAllowedOutputDTOBase { }

    [FunctionOutput]
    public class UserDistributeAllowedOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class VersionOutputDTO : VersionOutputDTOBase { }

    [FunctionOutput]
    public class VersionOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint8", "", 1)]
        public virtual byte ReturnValue1 { get; set; }
    }


}
