// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;

namespace RocketExplorer.Ethereum.LinkedListStorage.ContractDefinition
{
    public partial class DepositQueueKey : DepositQueueKeyBase { }

    public class DepositQueueKeyBase 
    {
        [Parameter("address", "receiver", 1)]
        public virtual string Receiver { get; set; }
        [Parameter("uint32", "validatorId", 2)]
        public virtual uint ValidatorId { get; set; }
    }
}
