// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Contracts.CQS;
using Nethereum.Contracts;
using System.Threading;

namespace RocketExplorer.Ethereum.LinkedListStorage.ContractDefinition
{


    public partial class LinkedListStorageDeployment : LinkedListStorageDeploymentBase
    {
        public LinkedListStorageDeployment() : base(BYTECODE) { }
        public LinkedListStorageDeployment(string byteCode) : base(byteCode) { }
    }

    public class LinkedListStorageDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = """
[
	{
		"inputs": [
			{
				"internalType": "contract RocketStorageInterface",
				"name": "_rocketStorageAddress",
				"type": "address"
			}
		],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			}
		],
		"name": "dequeueItem",
		"outputs": [
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "item",
				"type": "tuple"
			}
		],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "_item",
				"type": "tuple"
			}
		],
		"name": "enqueueItem",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			}
		],
		"name": "getHeadIndex",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueKey",
				"name": "_key",
				"type": "tuple"
			}
		],
		"name": "getIndexOf",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"internalType": "uint256",
				"name": "_index",
				"type": "uint256"
			}
		],
		"name": "getItem",
		"outputs": [
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			}
		],
		"name": "getLength",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "_value",
				"type": "tuple"
			}
		],
		"name": "getNextItem",
		"outputs": [
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "nextItem",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "_value",
				"type": "tuple"
			}
		],
		"name": "getPreviousItem",
		"outputs": [
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "previousItem",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			}
		],
		"name": "peekItem",
		"outputs": [
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue",
				"name": "item",
				"type": "tuple"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueKey",
				"name": "_key",
				"type": "tuple"
			}
		],
		"name": "removeItem",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_namespace",
				"type": "bytes32"
			},
			{
				"internalType": "uint256",
				"name": "_start",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "_count",
				"type": "uint256"
			}
		],
		"name": "scan",
		"outputs": [
			{
				"components": [
					{
						"internalType": "address",
						"name": "receiver",
						"type": "address"
					},
					{
						"internalType": "uint32",
						"name": "validatorId",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "suppliedValue",
						"type": "uint32"
					},
					{
						"internalType": "uint32",
						"name": "requestedValue",
						"type": "uint32"
					}
				],
				"internalType": "struct DepositQueueValue[]",
				"name": "entries",
				"type": "tuple[]"
			},
			{
				"internalType": "uint256",
				"name": "nextIndex",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "version",
		"outputs": [
			{
				"internalType": "uint8",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]
""";

        public LinkedListStorageDeploymentBase() : base(BYTECODE) { }
        public LinkedListStorageDeploymentBase(string byteCode) : base(byteCode) { }
        [Parameter("address", "_rocketStorageAddress", 1)]
        public virtual string RocketStorageAddress { get; set; }
    }

    public partial class DequeueItemFunction : DequeueItemFunctionBase { }

    [Function("dequeueItem", typeof(DequeueItemOutputDTO))]
    public class DequeueItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
    }

    public partial class EnqueueItemFunction : EnqueueItemFunctionBase { }

    [Function("enqueueItem")]
    public class EnqueueItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("tuple", "_item", 2)]
        public virtual DepositQueueValue Item { get; set; }
    }

    public partial class GetHeadIndexFunction : GetHeadIndexFunctionBase { }

    [Function("getHeadIndex", "uint256")]
    public class GetHeadIndexFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
    }

    public partial class GetIndexOfFunction : GetIndexOfFunctionBase { }

    [Function("getIndexOf", "uint256")]
    public class GetIndexOfFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("tuple", "_key", 2)]
        public virtual DepositQueueKey Key { get; set; }
    }

    public partial class GetItemFunction : GetItemFunctionBase { }

    [Function("getItem", typeof(GetItemOutputDTO))]
    public class GetItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("uint256", "_index", 2)]
        public virtual BigInteger Index { get; set; }
    }

    public partial class GetLengthFunction : GetLengthFunctionBase { }

    [Function("getLength", "uint256")]
    public class GetLengthFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
    }

    public partial class GetNextItemFunction : GetNextItemFunctionBase { }

    [Function("getNextItem", typeof(GetNextItemOutputDTO))]
    public class GetNextItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("tuple", "_value", 2)]
        public virtual DepositQueueValue Value { get; set; }
    }

    public partial class GetPreviousItemFunction : GetPreviousItemFunctionBase { }

    [Function("getPreviousItem", typeof(GetPreviousItemOutputDTO))]
    public class GetPreviousItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("tuple", "_value", 2)]
        public virtual DepositQueueValue Value { get; set; }
    }

    public partial class PeekItemFunction : PeekItemFunctionBase { }

    [Function("peekItem", typeof(PeekItemOutputDTO))]
    public class PeekItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
    }

    public partial class RemoveItemFunction : RemoveItemFunctionBase { }

    [Function("removeItem")]
    public class RemoveItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("tuple", "_key", 2)]
        public virtual DepositQueueKey Key { get; set; }
    }

    public partial class ScanFunction : ScanFunctionBase { }

    [Function("scan", typeof(ScanOutputDTO))]
    public class ScanFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_namespace", 1)]
        public virtual byte[] Namespace { get; set; }
        [Parameter("uint256", "_start", 2)]
        public virtual BigInteger Start { get; set; }
        [Parameter("uint256", "_count", 3)]
        public virtual BigInteger Count { get; set; }
    }

    public partial class VersionFunction : VersionFunctionBase { }

    [Function("version", "uint8")]
    public class VersionFunctionBase : FunctionMessage
    {

    }

    public partial class DequeueItemOutputDTO : DequeueItemOutputDTOBase { }

    [FunctionOutput]
    public class DequeueItemOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple", "item", 1)]
        public virtual DepositQueueValue Item { get; set; }
    }



    public partial class GetHeadIndexOutputDTO : GetHeadIndexOutputDTOBase { }

    [FunctionOutput]
    public class GetHeadIndexOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetIndexOfOutputDTO : GetIndexOfOutputDTOBase { }

    [FunctionOutput]
    public class GetIndexOfOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetItemOutputDTO : GetItemOutputDTOBase { }

    [FunctionOutput]
    public class GetItemOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple", "", 1)]
        public virtual DepositQueueValue ReturnValue1 { get; set; }
    }

    public partial class GetLengthOutputDTO : GetLengthOutputDTOBase { }

    [FunctionOutput]
    public class GetLengthOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetNextItemOutputDTO : GetNextItemOutputDTOBase { }

    [FunctionOutput]
    public class GetNextItemOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple", "nextItem", 1)]
        public virtual DepositQueueValue NextItem { get; set; }
    }

    public partial class GetPreviousItemOutputDTO : GetPreviousItemOutputDTOBase { }

    [FunctionOutput]
    public class GetPreviousItemOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple", "previousItem", 1)]
        public virtual DepositQueueValue PreviousItem { get; set; }
    }

    public partial class PeekItemOutputDTO : PeekItemOutputDTOBase { }

    [FunctionOutput]
    public class PeekItemOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple", "item", 1)]
        public virtual DepositQueueValue Item { get; set; }
    }



    public partial class ScanOutputDTO : ScanOutputDTOBase { }

    [FunctionOutput]
    public class ScanOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("tuple[]", "entries", 1)]
        public virtual List<DepositQueueValue> Entries { get; set; }
        [Parameter("uint256", "nextIndex", 2)]
        public virtual BigInteger NextIndex { get; set; }
    }

    public partial class VersionOutputDTO : VersionOutputDTOBase { }

    [FunctionOutput]
    public class VersionOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint8", "", 1)]
        public virtual byte ReturnValue1 { get; set; }
    }
}
