// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.Web3;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Contracts.CQS;
using Nethereum.Contracts.ContractHandlers;
using Nethereum.Contracts;
using System.Threading;
using RocketExplorer.Ethereum.AddressQueueStorage.ContractDefinition;

namespace RocketExplorer.Ethereum.AddressQueueStorage
{
    public partial class AddressQueueStorageService: AddressQueueStorageServiceBase
    {
        public static Task<TransactionReceipt> DeployContractAndWaitForReceiptAsync(Nethereum.Web3.IWeb3 web3, AddressQueueStorageDeployment addressQueueStorageDeployment, CancellationTokenSource cancellationTokenSource = null)
        {
            return web3.Eth.GetContractDeploymentHandler<AddressQueueStorageDeployment>().SendRequestAndWaitForReceiptAsync(addressQueueStorageDeployment, cancellationTokenSource);
        }

        public static Task<string> DeployContractAsync(Nethereum.Web3.IWeb3 web3, AddressQueueStorageDeployment addressQueueStorageDeployment)
        {
            return web3.Eth.GetContractDeploymentHandler<AddressQueueStorageDeployment>().SendRequestAsync(addressQueueStorageDeployment);
        }

        public static async Task<AddressQueueStorageService> DeployContractAndGetServiceAsync(Nethereum.Web3.IWeb3 web3, AddressQueueStorageDeployment addressQueueStorageDeployment, CancellationTokenSource cancellationTokenSource = null)
        {
            var receipt = await DeployContractAndWaitForReceiptAsync(web3, addressQueueStorageDeployment, cancellationTokenSource);
            return new AddressQueueStorageService(web3, receipt.ContractAddress);
        }

        public AddressQueueStorageService(Nethereum.Web3.IWeb3 web3, string contractAddress) : base(web3, contractAddress)
        {
        }

    }


    public partial class AddressQueueStorageServiceBase: ContractWeb3ServiceBase
    {

        public AddressQueueStorageServiceBase(Nethereum.Web3.IWeb3 web3, string contractAddress) : base(web3, contractAddress)
        {
        }

        public Task<BigInteger> CapacityQueryAsync(CapacityFunction capacityFunction, BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<CapacityFunction, BigInteger>(capacityFunction, blockParameter);
        }

        
        public virtual Task<BigInteger> CapacityQueryAsync(BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<CapacityFunction, BigInteger>(null, blockParameter);
        }

        public virtual Task<string> DequeueItemRequestAsync(DequeueItemFunction dequeueItemFunction)
        {
             return ContractHandler.SendRequestAsync(dequeueItemFunction);
        }

        public virtual Task<TransactionReceipt> DequeueItemRequestAndWaitForReceiptAsync(DequeueItemFunction dequeueItemFunction, CancellationTokenSource cancellationToken = null)
        {
             return ContractHandler.SendRequestAndWaitForReceiptAsync(dequeueItemFunction, cancellationToken);
        }

        public virtual Task<string> DequeueItemRequestAsync(byte[] key)
        {
            var dequeueItemFunction = new DequeueItemFunction();
                dequeueItemFunction.Key = key;
            
             return ContractHandler.SendRequestAsync(dequeueItemFunction);
        }

        public virtual Task<TransactionReceipt> DequeueItemRequestAndWaitForReceiptAsync(byte[] key, CancellationTokenSource cancellationToken = null)
        {
            var dequeueItemFunction = new DequeueItemFunction();
                dequeueItemFunction.Key = key;
            
             return ContractHandler.SendRequestAndWaitForReceiptAsync(dequeueItemFunction, cancellationToken);
        }

        public virtual Task<string> EnqueueItemRequestAsync(EnqueueItemFunction enqueueItemFunction)
        {
             return ContractHandler.SendRequestAsync(enqueueItemFunction);
        }

        public virtual Task<TransactionReceipt> EnqueueItemRequestAndWaitForReceiptAsync(EnqueueItemFunction enqueueItemFunction, CancellationTokenSource cancellationToken = null)
        {
             return ContractHandler.SendRequestAndWaitForReceiptAsync(enqueueItemFunction, cancellationToken);
        }

        public virtual Task<string> EnqueueItemRequestAsync(byte[] key, string value)
        {
            var enqueueItemFunction = new EnqueueItemFunction();
                enqueueItemFunction.Key = key;
                enqueueItemFunction.Value = value;
            
             return ContractHandler.SendRequestAsync(enqueueItemFunction);
        }

        public virtual Task<TransactionReceipt> EnqueueItemRequestAndWaitForReceiptAsync(byte[] key, string value, CancellationTokenSource cancellationToken = null)
        {
            var enqueueItemFunction = new EnqueueItemFunction();
                enqueueItemFunction.Key = key;
                enqueueItemFunction.Value = value;
            
             return ContractHandler.SendRequestAndWaitForReceiptAsync(enqueueItemFunction, cancellationToken);
        }

        public Task<BigInteger> GetIndexOfQueryAsync(GetIndexOfFunction getIndexOfFunction, BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<GetIndexOfFunction, BigInteger>(getIndexOfFunction, blockParameter);
        }

        
        public virtual Task<BigInteger> GetIndexOfQueryAsync(byte[] key, string value, BlockParameter blockParameter = null)
        {
            var getIndexOfFunction = new GetIndexOfFunction();
                getIndexOfFunction.Key = key;
                getIndexOfFunction.Value = value;
            
            return ContractHandler.QueryAsync<GetIndexOfFunction, BigInteger>(getIndexOfFunction, blockParameter);
        }

        public Task<string> GetItemQueryAsync(GetItemFunction getItemFunction, BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<GetItemFunction, string>(getItemFunction, blockParameter);
        }

        
        public virtual Task<string> GetItemQueryAsync(byte[] key, BigInteger index, BlockParameter blockParameter = null)
        {
            var getItemFunction = new GetItemFunction();
                getItemFunction.Key = key;
                getItemFunction.Index = index;
            
            return ContractHandler.QueryAsync<GetItemFunction, string>(getItemFunction, blockParameter);
        }

        public Task<BigInteger> GetLengthQueryAsync(GetLengthFunction getLengthFunction, BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<GetLengthFunction, BigInteger>(getLengthFunction, blockParameter);
        }

        
        public virtual Task<BigInteger> GetLengthQueryAsync(byte[] key, BlockParameter blockParameter = null)
        {
            var getLengthFunction = new GetLengthFunction();
                getLengthFunction.Key = key;
            
            return ContractHandler.QueryAsync<GetLengthFunction, BigInteger>(getLengthFunction, blockParameter);
        }

        public virtual Task<string> RemoveItemRequestAsync(RemoveItemFunction removeItemFunction)
        {
             return ContractHandler.SendRequestAsync(removeItemFunction);
        }

        public virtual Task<TransactionReceipt> RemoveItemRequestAndWaitForReceiptAsync(RemoveItemFunction removeItemFunction, CancellationTokenSource cancellationToken = null)
        {
             return ContractHandler.SendRequestAndWaitForReceiptAsync(removeItemFunction, cancellationToken);
        }

        public virtual Task<string> RemoveItemRequestAsync(byte[] key, string value)
        {
            var removeItemFunction = new RemoveItemFunction();
                removeItemFunction.Key = key;
                removeItemFunction.Value = value;
            
             return ContractHandler.SendRequestAsync(removeItemFunction);
        }

        public virtual Task<TransactionReceipt> RemoveItemRequestAndWaitForReceiptAsync(byte[] key, string value, CancellationTokenSource cancellationToken = null)
        {
            var removeItemFunction = new RemoveItemFunction();
                removeItemFunction.Key = key;
                removeItemFunction.Value = value;
            
             return ContractHandler.SendRequestAndWaitForReceiptAsync(removeItemFunction, cancellationToken);
        }

        public Task<byte> VersionQueryAsync(VersionFunction versionFunction, BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<VersionFunction, byte>(versionFunction, blockParameter);
        }

        
        public virtual Task<byte> VersionQueryAsync(BlockParameter blockParameter = null)
        {
            return ContractHandler.QueryAsync<VersionFunction, byte>(null, blockParameter);
        }

        public override List<Type> GetAllFunctionTypes()
        {
            return new List<Type>
            {
                typeof(CapacityFunction),
                typeof(DequeueItemFunction),
                typeof(EnqueueItemFunction),
                typeof(GetIndexOfFunction),
                typeof(GetItemFunction),
                typeof(GetLengthFunction),
                typeof(RemoveItemFunction),
                typeof(VersionFunction)
            };
        }

        public override List<Type> GetAllEventTypes()
        {
            return new List<Type>
            {

            };
        }

        public override List<Type> GetAllErrorTypes()
        {
            return new List<Type>
            {

            };
        }
    }
}
