// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Contracts.CQS;
using Nethereum.Contracts;
using System.Threading;

namespace RocketExplorer.Ethereum.rocketStorage.ContractDefinition
{


    public partial class RocketStorageDeployment : RocketStorageDeploymentBase
    {
        public RocketStorageDeployment() : base(BYTECODE) { }
        public RocketStorageDeployment(string byteCode) : base(byteCode) { }
    }

    public class RocketStorageDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = """
[
	{
		"inputs": [],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "address",
				"name": "oldGuardian",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "address",
				"name": "newGuardian",
				"type": "address"
			}
		],
		"name": "GuardianChanged",
		"type": "event"
	},
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": true,
				"internalType": "address",
				"name": "node",
				"type": "address"
			},
			{
				"indexed": true,
				"internalType": "address",
				"name": "withdrawalAddress",
				"type": "address"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "time",
				"type": "uint256"
			}
		],
		"name": "NodeWithdrawalAddressSet",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "uint256",
				"name": "_amount",
				"type": "uint256"
			}
		],
		"name": "addUint",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "confirmGuardian",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_nodeAddress",
				"type": "address"
			}
		],
		"name": "confirmWithdrawalAddress",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteAddress",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteBool",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteBytes",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteBytes32",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteInt",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteString",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "deleteUint",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getAddress",
		"outputs": [
			{
				"internalType": "address",
				"name": "r",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getBool",
		"outputs": [
			{
				"internalType": "bool",
				"name": "r",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getBytes",
		"outputs": [
			{
				"internalType": "bytes",
				"name": "",
				"type": "bytes"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getBytes32",
		"outputs": [
			{
				"internalType": "bytes32",
				"name": "r",
				"type": "bytes32"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getDeployedStatus",
		"outputs": [
			{
				"internalType": "bool",
				"name": "",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "getGuardian",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getInt",
		"outputs": [
			{
				"internalType": "int256",
				"name": "r",
				"type": "int256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_nodeAddress",
				"type": "address"
			}
		],
		"name": "getNodePendingWithdrawalAddress",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_nodeAddress",
				"type": "address"
			}
		],
		"name": "getNodeWithdrawalAddress",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getString",
		"outputs": [
			{
				"internalType": "string",
				"name": "",
				"type": "string"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getUint",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "r",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "address",
				"name": "_value",
				"type": "address"
			}
		],
		"name": "setAddress",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "bool",
				"name": "_value",
				"type": "bool"
			}
		],
		"name": "setBool",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "bytes",
				"name": "_value",
				"type": "bytes"
			}
		],
		"name": "setBytes",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "bytes32",
				"name": "_value",
				"type": "bytes32"
			}
		],
		"name": "setBytes32",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "setDeployedStatus",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_newAddress",
				"type": "address"
			}
		],
		"name": "setGuardian",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "int256",
				"name": "_value",
				"type": "int256"
			}
		],
		"name": "setInt",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "string",
				"name": "_value",
				"type": "string"
			}
		],
		"name": "setString",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "uint256",
				"name": "_value",
				"type": "uint256"
			}
		],
		"name": "setUint",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "address",
				"name": "_nodeAddress",
				"type": "address"
			},
			{
				"internalType": "address",
				"name": "_newWithdrawalAddress",
				"type": "address"
			},
			{
				"internalType": "bool",
				"name": "_confirm",
				"type": "bool"
			}
		],
		"name": "setWithdrawalAddress",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "uint256",
				"name": "_amount",
				"type": "uint256"
			}
		],
		"name": "subUint",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	}
]
""";
        public RocketStorageDeploymentBase() : base(BYTECODE) { }
        public RocketStorageDeploymentBase(string byteCode) : base(byteCode) { }

    }

    public partial class AddUintFunction : AddUintFunctionBase { }

    [Function("addUint")]
    public class AddUintFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("uint256", "_amount", 2)]
        public virtual BigInteger Amount { get; set; }
    }

    public partial class ConfirmGuardianFunction : ConfirmGuardianFunctionBase { }

    [Function("confirmGuardian")]
    public class ConfirmGuardianFunctionBase : FunctionMessage
    {

    }

    public partial class ConfirmWithdrawalAddressFunction : ConfirmWithdrawalAddressFunctionBase { }

    [Function("confirmWithdrawalAddress")]
    public class ConfirmWithdrawalAddressFunctionBase : FunctionMessage
    {
        [Parameter("address", "_nodeAddress", 1)]
        public virtual string NodeAddress { get; set; }
    }

    public partial class DeleteAddressFunction : DeleteAddressFunctionBase { }

    [Function("deleteAddress")]
    public class DeleteAddressFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class DeleteBoolFunction : DeleteBoolFunctionBase { }

    [Function("deleteBool")]
    public class DeleteBoolFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class DeleteBytesFunction : DeleteBytesFunctionBase { }

    [Function("deleteBytes")]
    public class DeleteBytesFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class DeleteBytes32Function : DeleteBytes32FunctionBase { }

    [Function("deleteBytes32")]
    public class DeleteBytes32FunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class DeleteIntFunction : DeleteIntFunctionBase { }

    [Function("deleteInt")]
    public class DeleteIntFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class DeleteStringFunction : DeleteStringFunctionBase { }

    [Function("deleteString")]
    public class DeleteStringFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class DeleteUintFunction : DeleteUintFunctionBase { }

    [Function("deleteUint")]
    public class DeleteUintFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetAddressFunction : GetAddressFunctionBase { }

    [Function("getAddress", "address")]
    public class GetAddressFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetBoolFunction : GetBoolFunctionBase { }

    [Function("getBool", "bool")]
    public class GetBoolFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetBytesFunction : GetBytesFunctionBase { }

    [Function("getBytes", "bytes")]
    public class GetBytesFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetBytes32Function : GetBytes32FunctionBase { }

    [Function("getBytes32", "bytes32")]
    public class GetBytes32FunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetDeployedStatusFunction : GetDeployedStatusFunctionBase { }

    [Function("getDeployedStatus", "bool")]
    public class GetDeployedStatusFunctionBase : FunctionMessage
    {

    }

    public partial class GetGuardianFunction : GetGuardianFunctionBase { }

    [Function("getGuardian", "address")]
    public class GetGuardianFunctionBase : FunctionMessage
    {

    }

    public partial class GetIntFunction : GetIntFunctionBase { }

    [Function("getInt", "int256")]
    public class GetIntFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetNodePendingWithdrawalAddressFunction : GetNodePendingWithdrawalAddressFunctionBase { }

    [Function("getNodePendingWithdrawalAddress", "address")]
    public class GetNodePendingWithdrawalAddressFunctionBase : FunctionMessage
    {
        [Parameter("address", "_nodeAddress", 1)]
        public virtual string NodeAddress { get; set; }
    }

    public partial class GetNodeWithdrawalAddressFunction : GetNodeWithdrawalAddressFunctionBase { }

    [Function("getNodeWithdrawalAddress", "address")]
    public class GetNodeWithdrawalAddressFunctionBase : FunctionMessage
    {
        [Parameter("address", "_nodeAddress", 1)]
        public virtual string NodeAddress { get; set; }
    }

    public partial class GetStringFunction : GetStringFunctionBase { }

    [Function("getString", "string")]
    public class GetStringFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetUintFunction : GetUintFunctionBase { }

    [Function("getUint", "uint256")]
    public class GetUintFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class SetAddressFunction : SetAddressFunctionBase { }

    [Function("setAddress")]
    public class SetAddressFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("address", "_value", 2)]
        public virtual string Value { get; set; }
    }

    public partial class SetBoolFunction : SetBoolFunctionBase { }

    [Function("setBool")]
    public class SetBoolFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("bool", "_value", 2)]
        public virtual bool Value { get; set; }
    }

    public partial class SetBytesFunction : SetBytesFunctionBase { }

    [Function("setBytes")]
    public class SetBytesFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("bytes", "_value", 2)]
        public virtual byte[] Value { get; set; }
    }

    public partial class SetBytes32Function : SetBytes32FunctionBase { }

    [Function("setBytes32")]
    public class SetBytes32FunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("bytes32", "_value", 2)]
        public virtual byte[] Value { get; set; }
    }

    public partial class SetDeployedStatusFunction : SetDeployedStatusFunctionBase { }

    [Function("setDeployedStatus")]
    public class SetDeployedStatusFunctionBase : FunctionMessage
    {

    }

    public partial class SetGuardianFunction : SetGuardianFunctionBase { }

    [Function("setGuardian")]
    public class SetGuardianFunctionBase : FunctionMessage
    {
        [Parameter("address", "_newAddress", 1)]
        public virtual string NewAddress { get; set; }
    }

    public partial class SetIntFunction : SetIntFunctionBase { }

    [Function("setInt")]
    public class SetIntFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("int256", "_value", 2)]
        public virtual BigInteger Value { get; set; }
    }

    public partial class SetStringFunction : SetStringFunctionBase { }

    [Function("setString")]
    public class SetStringFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("string", "_value", 2)]
        public virtual string Value { get; set; }
    }

    public partial class SetUintFunction : SetUintFunctionBase { }

    [Function("setUint")]
    public class SetUintFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("uint256", "_value", 2)]
        public virtual BigInteger Value { get; set; }
    }

    public partial class SetWithdrawalAddressFunction : SetWithdrawalAddressFunctionBase { }

    [Function("setWithdrawalAddress")]
    public class SetWithdrawalAddressFunctionBase : FunctionMessage
    {
        [Parameter("address", "_nodeAddress", 1)]
        public virtual string NodeAddress { get; set; }
        [Parameter("address", "_newWithdrawalAddress", 2)]
        public virtual string NewWithdrawalAddress { get; set; }
        [Parameter("bool", "_confirm", 3)]
        public virtual bool Confirm { get; set; }
    }

    public partial class SubUintFunction : SubUintFunctionBase { }

    [Function("subUint")]
    public class SubUintFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("uint256", "_amount", 2)]
        public virtual BigInteger Amount { get; set; }
    }

    public partial class GuardianChangedEventDTO : GuardianChangedEventDTOBase { }

    [Event("GuardianChanged")]
    public class GuardianChangedEventDTOBase : IEventDTO
    {
        [Parameter("address", "oldGuardian", 1, false )]
        public virtual string OldGuardian { get; set; }
        [Parameter("address", "newGuardian", 2, false )]
        public virtual string NewGuardian { get; set; }
    }

    public partial class NodeWithdrawalAddressSetEventDTO : NodeWithdrawalAddressSetEventDTOBase { }

    [Event("NodeWithdrawalAddressSet")]
    public class NodeWithdrawalAddressSetEventDTOBase : IEventDTO
    {
        [Parameter("address", "node", 1, true )]
        public virtual string Node { get; set; }
        [Parameter("address", "withdrawalAddress", 2, true )]
        public virtual string WithdrawalAddress { get; set; }
        [Parameter("uint256", "time", 3, false )]
        public virtual BigInteger Time { get; set; }
    }





















    public partial class GetAddressOutputDTO : GetAddressOutputDTOBase { }

    [FunctionOutput]
    public class GetAddressOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("address", "r", 1)]
        public virtual string R { get; set; }
    }

    public partial class GetBoolOutputDTO : GetBoolOutputDTOBase { }

    [FunctionOutput]
    public class GetBoolOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "r", 1)]
        public virtual bool R { get; set; }
    }

    public partial class GetBytesOutputDTO : GetBytesOutputDTOBase { }

    [FunctionOutput]
    public class GetBytesOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bytes", "", 1)]
        public virtual byte[] ReturnValue1 { get; set; }
    }

    public partial class GetBytes32OutputDTO : GetBytes32OutputDTOBase { }

    [FunctionOutput]
    public class GetBytes32OutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bytes32", "r", 1)]
        public virtual byte[] R { get; set; }
    }

    public partial class GetDeployedStatusOutputDTO : GetDeployedStatusOutputDTOBase { }

    [FunctionOutput]
    public class GetDeployedStatusOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("bool", "", 1)]
        public virtual bool ReturnValue1 { get; set; }
    }

    public partial class GetGuardianOutputDTO : GetGuardianOutputDTOBase { }

    [FunctionOutput]
    public class GetGuardianOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("address", "", 1)]
        public virtual string ReturnValue1 { get; set; }
    }

    public partial class GetIntOutputDTO : GetIntOutputDTOBase { }

    [FunctionOutput]
    public class GetIntOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("int256", "r", 1)]
        public virtual BigInteger R { get; set; }
    }

    public partial class GetNodePendingWithdrawalAddressOutputDTO : GetNodePendingWithdrawalAddressOutputDTOBase { }

    [FunctionOutput]
    public class GetNodePendingWithdrawalAddressOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("address", "", 1)]
        public virtual string ReturnValue1 { get; set; }
    }

    public partial class GetNodeWithdrawalAddressOutputDTO : GetNodeWithdrawalAddressOutputDTOBase { }

    [FunctionOutput]
    public class GetNodeWithdrawalAddressOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("address", "", 1)]
        public virtual string ReturnValue1 { get; set; }
    }

    public partial class GetStringOutputDTO : GetStringOutputDTOBase { }

    [FunctionOutput]
    public class GetStringOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("string", "", 1)]
        public virtual string ReturnValue1 { get; set; }
    }

    public partial class GetUintOutputDTO : GetUintOutputDTOBase { }

    [FunctionOutput]
    public class GetUintOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "r", 1)]
        public virtual BigInteger R { get; set; }
    }






















}
