// <auto-generated>
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Contracts.CQS;
using Nethereum.Contracts;
using System.Threading;

namespace RocketExplorer.Ethereum.AddressSetStorage.ContractDefinition
{


    public partial class AddressSetStorageDeployment : AddressSetStorageDeploymentBase
    {
        public AddressSetStorageDeployment() : base(BYTECODE) { }
        public AddressSetStorageDeployment(string byteCode) : base(byteCode) { }
    }

    public class AddressSetStorageDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = """
[
	{
		"inputs": [
			{
				"internalType": "contract RocketStorageInterface",
				"name": "_rocketStorageAddress",
				"type": "address"
			}
		],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "address",
				"name": "_value",
				"type": "address"
			}
		],
		"name": "addItem",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			}
		],
		"name": "getCount",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "address",
				"name": "_value",
				"type": "address"
			}
		],
		"name": "getIndexOf",
		"outputs": [
			{
				"internalType": "int256",
				"name": "",
				"type": "int256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "uint256",
				"name": "_index",
				"type": "uint256"
			}
		],
		"name": "getItem",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "bytes32",
				"name": "_key",
				"type": "bytes32"
			},
			{
				"internalType": "address",
				"name": "_value",
				"type": "address"
			}
		],
		"name": "removeItem",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "version",
		"outputs": [
			{
				"internalType": "uint8",
				"name": "",
				"type": "uint8"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]
""";
        public AddressSetStorageDeploymentBase() : base(BYTECODE) { }
        public AddressSetStorageDeploymentBase(string byteCode) : base(byteCode) { }
        [Parameter("address", "_rocketStorageAddress", 1)]
        public virtual string RocketStorageAddress { get; set; }
    }

    public partial class AddItemFunction : AddItemFunctionBase { }

    [Function("addItem")]
    public class AddItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("address", "_value", 2)]
        public virtual string Value { get; set; }
    }

    public partial class GetCountFunction : GetCountFunctionBase { }

    [Function("getCount", "uint256")]
    public class GetCountFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
    }

    public partial class GetIndexOfFunction : GetIndexOfFunctionBase { }

    [Function("getIndexOf", "int256")]
    public class GetIndexOfFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("address", "_value", 2)]
        public virtual string Value { get; set; }
    }

    public partial class GetItemFunction : GetItemFunctionBase { }

    [Function("getItem", "address")]
    public class GetItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("uint256", "_index", 2)]
        public virtual BigInteger Index { get; set; }
    }

    public partial class RemoveItemFunction : RemoveItemFunctionBase { }

    [Function("removeItem")]
    public class RemoveItemFunctionBase : FunctionMessage
    {
        [Parameter("bytes32", "_key", 1)]
        public virtual byte[] Key { get; set; }
        [Parameter("address", "_value", 2)]
        public virtual string Value { get; set; }
    }

    public partial class VersionFunction : VersionFunctionBase { }

    [Function("version", "uint8")]
    public class VersionFunctionBase : FunctionMessage
    {

    }



    public partial class GetCountOutputDTO : GetCountOutputDTOBase { }

    [FunctionOutput]
    public class GetCountOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetIndexOfOutputDTO : GetIndexOfOutputDTOBase { }

    [FunctionOutput]
    public class GetIndexOfOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("int256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }

    public partial class GetItemOutputDTO : GetItemOutputDTOBase { }

    [FunctionOutput]
    public class GetItemOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("address", "", 1)]
        public virtual string ReturnValue1 { get; set; }
    }



    public partial class VersionOutputDTO : VersionOutputDTOBase { }

    [FunctionOutput]
    public class VersionOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint8", "", 1)]
        public virtual byte ReturnValue1 { get; set; }
    }
}
